

networks = [
    ('A&E', '/shows?Show[network_id]=29&page=1'),
    ('ABC', '/shows?Show[network_id]=3&page=1'),
    ('Adult Swim', '/shows?Show[network_id]=10&page=1'),
    ('AHC', '/shows?Show[network_id]=229&page=1'),
    ('Al Jazeera America', '/shows?Show[network_id]=169&page=1'),
    ('AMC', '/shows?Show[network_id]=20&page=1'),
    ('Animal Planet', '/shows?Show[network_id]=92&page=1'),
    ('Audience Network', '/shows?Show[network_id]=31&page=1'),
    ('AXS TV', '/shows?Show[network_id]=170&page=1'),
    ('BBC America', '/shows?Show[network_id]=15&page=1'),
    ('BET', '/shows?Show[network_id]=56&page=1'),
    ('Bloomberg TV', '/shows?Show[network_id]=172&page=1'),
    ('Boomerang', '/shows?Show[network_id]=456&page=1'),
    ('BOUNCE TV', '/shows?Show[network_id]=261&page=1'),
    ('Bravo', '/shows?Show[network_id]=52&page=1'),
    ('BYU Television', '/shows?Show[network_id]=467&page=1'),
    ('C-SPAN2', '/shows?Show[network_id]=1514&page=1'),
    ('Cartoon Network', '/shows?Show[network_id]=11&page=1'),
    ('CBS', '/shows?Show[network_id]=2&page=1'),
    ('CBS Sports Network', '/shows?Show[network_id]=272&page=1'),
    ('Cinemax', '/shows?Show[network_id]=19&page=1'),
    ('CMT', '/shows?Show[network_id]=173&page=1'),
    ('CNBC', '/shows?Show[network_id]=93&page=1'),
    ('CNN', '/shows?Show[network_id]=40&page=1'),
    ('Comedy Central', '/shows?Show[network_id]=23&page=1'),
    ('Cooking Channel', '/shows?Show[network_id]=174&page=1'),
    ('Create', '/shows?Show[network_id]=175&page=1'),
    ('Destination America', '/shows?Show[network_id]=107&page=1'),
    ('Discovery Channel', '/shows?Show[network_id]=66&page=1'),
    ('Discovery Family', '/shows?Show[network_id]=176&page=1'),
    ('Discovery Life', '/shows?Show[network_id]=177&page=1'),
    ('Disney Channel', '/shows?Show[network_id]=78&page=1'),
    ('Disney Junior', '/shows?Show[network_id]=1039&page=1'),
    ('Disney XD', '/shows?Show[network_id]=25&page=1'),
    ('DIY Network', '/shows?Show[network_id]=90&page=1'),
    ('E!', '/shows?Show[network_id]=43&page=1'),
    ('El Rey Network', '/shows?Show[network_id]=21&page=1'),
    ('Epix', '/shows?Show[network_id]=253&page=1'),
    ('ESPN', '/shows?Show[network_id]=39&page=1'),
    ('ESPN2', '/shows?Show[network_id]=180&page=1'),
    ('ESPNEWS', '/shows?Show[network_id]=181&page=1'),
    ('Esquire Network', '/shows?Show[network_id]=184&page=1'),
    ('Estrella TV', '/shows?Show[network_id]=535&page=1'),
    ('Food Network', '/shows?Show[network_id]=81&page=1'),
    ('Fox', '/shows?Show[network_id]=4&page=1'),
    ('Fox Business Network', '/shows?Show[network_id]=524&page=1'),
    ('Fox News Channel', '/shows?Show[network_id]=185&page=1'),
    ('Fox Sports 1', '/shows?Show[network_id]=95&page=1'),
    ('Fox Sports SUN', '/shows?Show[network_id]=1047&page=1'),
    ('FreeForm', '/shows?Show[network_id]=26&page=1'),
    ('FUSE TV', '/shows?Show[network_id]=186&page=1'),
    ('Fusion', '/shows?Show[network_id]=187&page=1'),
    ('FX', '/shows?Show[network_id]=13&page=1'),
    ('FXX', '/shows?Show[network_id]=47&page=1'),
    ('Fyi,', '/shows?Show[network_id]=125&page=1'),
    ('G4', '/shows?Show[network_id]=248&page=1'),
    ('Game Show Network', '/shows?Show[network_id]=189&page=1'),
    ('Golf Channel', '/shows?Show[network_id]=188&page=1'),
    ('Great American Country', '/shows?Show[network_id]=103&page=1'),
    ('H2', '/shows?Show[network_id]=74&page=1'),
    ('Hallmark Channel', '/shows?Show[network_id]=50&page=1'),
    ('Hallmark Movies & Mysteries', '/shows?Show[network_id]=252&page=1'),
    ('HBO', '/shows?Show[network_id]=8&page=1'),
    ('HBO Family', '/shows?Show[network_id]=190&page=1'),
    ('HGTV', '/shows?Show[network_id]=192&page=1'),
    ('History', '/shows?Show[network_id]=53&page=1'),
    ('HLN', '/shows?Show[network_id]=193&page=1'),
    ('IFC', '/shows?Show[network_id]=65&page=1'),
    ('Insp', '/shows?Show[network_id]=660&page=1'),
    ('Investigation Discovery', '/shows?Show[network_id]=89&page=1'),
    ('JTV', '/shows?Show[network_id]=1626&page=1'),
    ('KCET', '/shows?Show[network_id]=975&page=1'),
    ('Lifetime', '/shows?Show[network_id]=18&page=1'),
    ('Lifetime Movies', '/shows?Show[network_id]=232&page=1'),
    ('Logo TV', '/shows?Show[network_id]=117&page=1'),
    ('MAVTV', '/shows?Show[network_id]=739&page=1'),
    ('Me-TV', '/shows?Show[network_id]=198&page=1'),
    ('MotorTrend', '/shows?Show[network_id]=142&page=1'),
    ('MSNBC', '/shows?Show[network_id]=201&page=1'),
    ('MTV', '/shows?Show[network_id]=22&page=1'),
    ('MTV2', '/shows?Show[network_id]=145&page=1'),
    ('National Geographic Channel', '/shows?Show[network_id]=42&page=1'),
    ('National Geographic WILD', '/shows?Show[network_id]=83&page=1'),
    ('NBC', '/shows?Show[network_id]=1&page=1'),
    ('NBCSN', '/shows?Show[network_id]=104&page=1'),
    ('NFL Network', '/shows?Show[network_id]=205&page=1'),
    ('Nick Jr.', '/shows?Show[network_id]=206&page=1'),
    ('Nickelodeon', '/shows?Show[network_id]=27&page=1'),
    ('Nicktoons', '/shows?Show[network_id]=73&page=1'),
    ('Oprah Winfrey Network', '/shows?Show[network_id]=236&page=1'),
    ('Ora TV', '/shows?Show[network_id]=1368&page=1'),
    ('Outdoor Channel', '/shows?Show[network_id]=207&page=1'),
    ('Ovation', '/shows?Show[network_id]=208&page=1'),
    ('Oxygen', '/shows?Show[network_id]=79&page=1'),
    ('Palladia', '/shows?Show[network_id]=736&page=1'),
    ('Paramount Network', '/shows?Show[network_id]=34&page=1'),
    ('Pay-Per-View', '/shows?Show[network_id]=138&page=1'),
    ('PBS', '/shows?Show[network_id]=85&page=1'),
    ('Pivot', '/shows?Show[network_id]=211&page=1'),
    ('Playboy TV', '/shows?Show[network_id]=1035&page=1'),
    ('Pop', '/shows?Show[network_id]=88&page=1'),
    ('Pursuit Channel', '/shows?Show[network_id]=733&page=1'),
    ('Qubo', '/shows?Show[network_id]=212&page=1'),
    ('REELZ', '/shows?Show[network_id]=75&page=1'),
    ('REVOLT', '/shows?Show[network_id]=520&page=1'),
    ('Science', '/shows?Show[network_id]=77&page=1'),
    ('Showtime', '/shows?Show[network_id]=9&page=1'),
    ('Smithsonian Channel', '/shows?Show[network_id]=86&page=1'),
    ('Spectrum', '/shows?Show[network_id]=1620&page=1'),
    ('Sportsman Channel', '/shows?Show[network_id]=217&page=1'),
    ('Starz', '/shows?Show[network_id]=17&page=1'),
    ('Sundance TV', '/shows?Show[network_id]=33&page=1'),
    ('Syfy', '/shows?Show[network_id]=16&page=1'),
    ('Syndication', '/shows?Show[network_id]=72&page=1'),
    ('TBN', '/shows?Show[network_id]=758&page=1'),
    ('TBS', '/shows?Show[network_id]=32&page=1'),
    ('Telemundo', '/shows?Show[network_id]=219&page=1'),
    ('The CW', '/shows?Show[network_id]=5&page=1'),
    ('The Weather Channel', '/shows?Show[network_id]=228&page=1'),
    ('TLC', '/shows?Show[network_id]=80&page=1'),
    ('TNT', '/shows?Show[network_id]=14&page=1'),
    ('Travel Channel', '/shows?Show[network_id]=82&page=1'),
    ('truTV', '/shows?Show[network_id]=84&page=1'),
    ('TV Guide Channel', '/shows?Show[network_id]=455&page=1'),
    ('TV Land', '/shows?Show[network_id]=57&page=1'),
    ('TV One', '/shows?Show[network_id]=224&page=1'),
    ('UniMas', '/shows?Show[network_id]=225&page=1'),
    ('Universal Kids', '/shows?Show[network_id]=342&page=1'),
    ('Univision', '/shows?Show[network_id]=226&page=1'),
    ('UP TV', '/shows?Show[network_id]=227&page=1'),
    ('USA Network', '/shows?Show[network_id]=30&page=1'),
    ('VH1', '/shows?Show[network_id]=55&page=1'),
    ('VH1 Classic', '/shows?Show[network_id]=557&page=1'),
    ('Viceland', '/shows?Show[network_id]=1006&page=1'),
    ('We tv', '/shows?Show[network_id]=122&page=1'),
    ('WGBH-TV', '/shows?Show[network_id]=1089&page=1'),
    ('WGN America', '/shows?Show[network_id]=28&page=1'),
    ('World', '/shows?Show[network_id]=430&page=1')
]


webchannels = [
    ("3waytv.tv", "/shows?Show[webChannel_id]=87&page=1"),
    ("20th Television", "/shows?Show[webChannel_id]=178&page=1"),
    ("ABC iView", "/shows?Show[webChannel_id]=149&page=1"),
    ("ABC.com", "/shows?Show[webChannel_id]=95&page=1"),
    ("AbemaTV", "/shows?Show[webChannel_id]=135&page=1"),
    ("Acorn TV", "/shows?Show[webChannel_id]=129&page=1"),
    ("AdultSwim.com", "/shows?Show[webChannel_id]=110&page=1"),
    ("All 4", "/shows?Show[webChannel_id]=52&page=1"),
    ("ALLBLK", "/shows?Show[webChannel_id]=209&page=1"),
    ("Amazon", "/shows?Show[webChannel_id]=3&page=1"),
    ("AMC Premiere", "/shows?Show[webChannel_id]=250&page=1"),
    ("AMC+", "/shows?Show[webChannel_id]=453&page=1"),
    ("amc.com", "/shows?Show[webChannel_id]=142&page=1"),
    ("AOL On", "/shows?Show[webChannel_id]=28&page=1"),
    ("Apple TV+", "/shows?Show[webChannel_id]=310&page=1"),
    ("Atom.com", "/shows?Show[webChannel_id]=48&page=1"),
    ("B/RLive", "/shows?Show[webChannel_id]=411&page=1"),
    ("BBC iPlayer", "/shows?Show[webChannel_id]=26&page=1"),
    ("BBC Three", "/shows?Show[webChannel_id]=71&page=1"),
    ("BET+", "/shows?Show[webChannel_id]=351&page=1"),
    ("Bilibili", "/shows?Show[webChannel_id]=51&page=1"),
    ("Blackpills", "/shows?Show[webChannel_id]=186&page=1"),
    ("Blim", "/shows?Show[webChannel_id]=197&page=1"),
    ("Blip", "/shows?Show[webChannel_id]=40&page=1"),
    ("BluTV", "/shows?Show[webChannel_id]=222&page=1"),
    ("bon appetit video", "/shows?Show[webChannel_id]=303&page=1"),
    ("Brat", "/shows?Show[webChannel_id]=274&page=1"),
    ("BrokenSaints.com", "/shows?Show[webChannel_id]=198&page=1"),
    ("BYUtv", "/shows?Show[webChannel_id]=223&page=1"),
    ("C More Finland", "/shows?Show[webChannel_id]=306&page=1"),
    ("C More", "/shows?Show[webChannel_id]=170&page=1"),
    ("Cartoon Hangover", "/shows?Show[webChannel_id]=284&page=1"),
    ("CBC Gem", "/shows?Show[webChannel_id]=300&page=1"),
    ("CBC", "/shows?Show[webChannel_id]=108&page=1"),
    ("CBS All Access", "/shows?Show[webChannel_id]=107&page=1"),
    ("CC: Studios", "/shows?Show[webChannel_id]=73&page=1"),
    ("Channel 101", "/shows?Show[webChannel_id]=217&page=1"),
    ("CHIKARAtopia", "/shows?Show[webChannel_id]=163&page=1"),
    ("Collegehumor", "/shows?Show[webChannel_id]=228&page=1"),
    ("Complex", "/shows?Show[webChannel_id]=199&page=1"),
    ("CONtv", "/shows?Show[webChannel_id]=111&page=1"),
    ("Crackle Spotlight", "/shows?Show[webChannel_id]=185&page=1"),
    ("Crackle", "/shows?Show[webChannel_id]=4&page=1"),
    ("CraveTV", "/shows?Show[webChannel_id]=109&page=1"),
    ("CuriosityStream", "/shows?Show[webChannel_id]=188&page=1"),
    ("CW Seed", "/shows?Show[webChannel_id]=13&page=1"),
    ("Dailymotion", "/shows?Show[webChannel_id]=307&page=1"),
    ("davidlynch.com", "/shows?Show[webChannel_id]=183&page=1"),
    ("Daybreak2012.com", "/shows?Show[webChannel_id]=60&page=1"),
    ("DC Universe", "/shows?Show[webChannel_id]=187&page=1"),
    ("Dekkoo", "/shows?Show[webChannel_id]=174&page=1"),
    ("DirecTV Now", "/shows?Show[webChannel_id]=276&page=1"),
    ("Discovery+", "/shows?Show[webChannel_id]=436&page=1"),
    ("DisneyNOW", "/shows?Show[webChannel_id]=83&page=1"),
    ("Dove Channel", "/shows?Show[webChannel_id]=175&page=1"),
    ("Dramafever", "/shows?Show[webChannel_id]=128&page=1"),
    ("Dropout", "/shows?Show[webChannel_id]=311&page=1"),
    ("Elisa Viihde", "/shows?Show[webChannel_id]=293&page=1"),
    ("EntertainTV", "/shows?Show[webChannel_id]=247&page=1"),
    ("EPIX.com", "/shows?Show[webChannel_id]=503&page=1"),
    ("ESPN3", "/shows?Show[webChannel_id]=17&page=1"),
    ("ESPN+", "/shows?Show[webChannel_id]=265&page=1"),
    ("Explosm", "/shows?Show[webChannel_id]=29&page=1"),
    ("Eyeslicer.com", "/shows?Show[webChannel_id]=236&page=1"),
    ("Fangdango", "/shows?Show[webChannel_id]=33&page=1"),
    ("FemininFeminin.com", "/shows?Show[webChannel_id]=61&page=1"),
    ("FilmOn", "/shows?Show[webChannel_id]=278&page=1"),
    ("Floslam", "/shows?Show[webChannel_id]=159&page=1"),
    ("Fox Nation", "/shows?Show[webChannel_id]=509&page=1"),
    ("FOXNow", "/shows?Show[webChannel_id]=179&page=1"),
    ("France TV Slash", "/shows?Show[webChannel_id]=252&page=1"),
    ("Freeform", "/shows?Show[webChannel_id]=145&page=1"),
    ("fullscreen", "/shows?Show[webChannel_id]=90&page=1"),
    ("Funimation", "/shows?Show[webChannel_id]=89&page=1"),
    ("Funny or Die", "/shows?Show[webChannel_id]=36&page=1"),
    ("fxnetworks", "/shows?Show[webChannel_id]=141&page=1"),
    ("GAS Digital", "/shows?Show[webChannel_id]=234&page=1"),
    ("Geek and Sundry", "/shows?Show[webChannel_id]=157&page=1"),
    ("GeekNation", "/shows?Show[webChannel_id]=44&page=1"),
    ("Globo Play", "/shows?Show[webChannel_id]=131&page=1"),
    ("Go90", "/shows?Show[webChannel_id]=85&page=1"),
    ("Hallmark Channel Everywhere", "/shows?Show[webChannel_id]=98&page=1"),
    ("Hallmark Movies Now", "/shows?Show[webChannel_id]=279&page=1"),
    ("Halo Waypoint", "/shows?Show[webChannel_id]=62&page=1"),
    ("Hasbro Studios", "/shows?Show[webChannel_id]=24&page=1"),
    ("HBO Go", "/shows?Show[webChannel_id]=22&page=1"),
    ("HDnet", "/shows?Show[webChannel_id]=176&page=1"),
    ("Hill.TV", "/shows?Show[webChannel_id]=389&page=1"),
    ("History Channel", "/shows?Show[webChannel_id]=94&page=1"),
    ("Hotstar", "/shows?Show[webChannel_id]=164&page=1"),
    ("Hulu Japan", "/shows?Show[webChannel_id]=235&page=1"),
    ("Hulu", "/shows?Show[webChannel_id]=2&page=1"),
    ("ICI Tou.tv", "/shows?Show[webChannel_id]=301&page=1"),
    ("IMDb TV", "/shows?Show[webChannel_id]=251&page=1"),
    ("iQiyi", "/shows?Show[webChannel_id]=67&page=1"),
    ("ITV Hub", "/shows?Show[webChannel_id]=54&page=1"),
    ("Jash", "/shows?Show[webChannel_id]=345&page=1"),
    ("Jauntvr", "/shows?Show[webChannel_id]=156&page=1"),
    ("Jetix Web Channel", "/shows?Show[webChannel_id]=55&page=1"),
    ("Kartoon Channel!", "/shows?Show[webChannel_id]=451&page=1"),
    ("Koldcast.tv", "/shows?Show[webChannel_id]=147&page=1"),
    ("KPN Presenteert", "/shows?Show[webChannel_id]=130&page=1"),
    ("LINE TV", "/shows?Show[webChannel_id]=88&page=1"),
    ("loboonline.com", "/shows?Show[webChannel_id]=144&page=1"),
    ("LouisCK.net", "/shows?Show[webChannel_id]=75&page=1"),
    ("LStudio.com", "/shows?Show[webChannel_id]=39&page=1"),
    ("Machinima.com", "/shows?Show[webChannel_id]=8&page=1"),
    ("Magnolia Network", "/shows?Show[webChannel_id]=460&page=1"),
    ("Maker.tv", "/shows?Show[webChannel_id]=41&page=1"),
    ("Mango TV", "/shows?Show[webChannel_id]=226&page=1"),
    ("Maxdome", "/shows?Show[webChannel_id]=137&page=1"),
    ("Melon", "/shows?Show[webChannel_id]=240&page=1"),
    ("MOJO HD", "/shows?Show[webChannel_id]=239&page=1"),
    ("Motor Trend On Demand", "/shows?Show[webChannel_id]=200&page=1"),
    ("Movistar+", "/shows?Show[webChannel_id]=169&page=1"),
    ("MTV.com", "/shows?Show[webChannel_id]=260&page=1"),
    ("Munchies", "/shows?Show[webChannel_id]=225&page=1"),
    ("mylifetime.com", "/shows?Show[webChannel_id]=181&page=1"),
    ("Naver TVCast", "/shows?Show[webChannel_id]=30&page=1"),
    ("NBC News Signal", "/shows?Show[webChannel_id]=292&page=1"),
    ("NBC.com", "/shows?Show[webChannel_id]=11&page=1"),
    ("Netflix", "/shows?Show[webChannel_id]=1&page=1"),
    ("Nick App", "/shows?Show[webChannel_id]=263&page=1"),
    ("Niconico", "/shows?Show[webChannel_id]=93&page=1"),
    ("NRK.no", "/shows?Show[webChannel_id]=238&page=1"),
    ("Null Video", "/shows?Show[webChannel_id]=296&page=1"),
    ("Olleh TV", "/shows?Show[webChannel_id]=258&page=1"),
    ("PantaYA", "/shows?Show[webChannel_id]=334&page=1"),
    ("PBS", "/shows?Show[webChannel_id]=420&page=1"),
    ("Peacock", "/shows?Show[webChannel_id]=347&page=1"),
    ("Pioneer One TV", "/shows?Show[webChannel_id]=34&page=1"),
    ("piperspicks.tv", "/shows?Show[webChannel_id]=194&page=1"),
    ("Playstation", "/shows?Show[webChannel_id]=14&page=1"),
    ("Pluto TV", "/shows?Show[webChannel_id]=338&page=1"),
    ("Pokerstars.com", "/shows?Show[webChannel_id]=206&page=1"),
    ("Project Alpha", "/shows?Show[webChannel_id]=259&page=1"),
    ("projectphoenix.tv", "/shows?Show[webChannel_id]=127&page=1"),
    ("Puhu TV", "/shows?Show[webChannel_id]=153&page=1"),
    ("Pureflix", "/shows?Show[webChannel_id]=485&page=1"),
    ("Rides.tv", "/shows?Show[webChannel_id]=360&page=1"),
    ("Rooster Teeth", "/shows?Show[webChannel_id]=32&page=1"),
    ("RTBF Webcreation", "/shows?Show[webChannel_id]=101&page=1"),
    ("Rutube", "/shows?Show[webChannel_id]=99&page=1"),
    ("ScreenMagic TV", "/shows?Show[webChannel_id]=201&page=1"),
    ("Seeso", "/shows?Show[webChannel_id]=77&page=1"),
    ("ShahrzadSeries.com", "/shows?Show[webChannel_id]=80&page=1"),
    ("ShoutFactoryTV", "/shows?Show[webChannel_id]=19&page=1"),
    ("Showtime on Demand", "/shows?Show[webChannel_id]=315&page=1"),
    ("Shudder", "/shows?Show[webChannel_id]=213&page=1"),
    ("Sky Go (DE)", "/shows?Show[webChannel_id]=295&page=1"),
    ("Sky Go", "/shows?Show[webChannel_id]=117&page=1"),
    ("Smithsonian Earth", "/shows?Show[webChannel_id]=282&page=1"),
    ("Sohu TV", "/shows?Show[webChannel_id]=50&page=1"),
    ("SpaceJanitors.com", "/shows?Show[webChannel_id]=63&page=1"),
    ("Spectrum On Demand", "/shows?Show[webChannel_id]=316&page=1"),
    ("spike.com", "/shows?Show[webChannel_id]=193&page=1"),
    ("Spotify", "/shows?Show[webChannel_id]=146&page=1"),
    ("Sprint TV", "/shows?Show[webChannel_id]=362&page=1"),
    ("Stan", "/shows?Show[webChannel_id]=64&page=1"),
    ("startrekcontinues.com", "/shows?Show[webChannel_id]=16&page=1"),
    ("StarzPlay", "/shows?Show[webChannel_id]=46&page=1"),
    ("stnv.de", "/shows?Show[webChannel_id]=121&page=1"),
    ("Stream.cz", "/shows?Show[webChannel_id]=38&page=1"),
    ("Studio 4", "/shows?Show[webChannel_id]=297&page=1"),
    ("SundanceTV", "/shows?Show[webChannel_id]=244&page=1"),
    ("Super Deluxe", "/shows?Show[webChannel_id]=214&page=1"),
    ("SVT Play", "/shows?Show[webChannel_id]=190&page=1"),
    ("SwearNet", "/shows?Show[webChannel_id]=464&page=1"),
    ("Syfy", "/shows?Show[webChannel_id]=49&page=1"),
    ("TBS.com", "/shows?Show[webChannel_id]=224&page=1"),
    ("TED.com", "/shows?Show[webChannel_id]=105&page=1"),
    ("Tello", "/shows?Show[webChannel_id]=242&page=1"),
    ("Tencent QQ", "/shows?Show[webChannel_id]=104&page=1"),
    ("The Fantasy Network", "/shows?Show[webChannel_id]=305&page=1"),
    ("The Gizmoplex", "/shows?Show[webChannel_id]=475&page=1"),
    ("The Zeus Network", "/shows?Show[webChannel_id]=312&page=1"),
    ("TheBlaze", "/shows?Show[webChannel_id]=23&page=1"),
    ("TheWB.com", "/shows?Show[webChannel_id]=182&page=1"),
    ("TLCgo", "/shows?Show[webChannel_id]=180&page=1"),
    ("ToonsTV", "/shows?Show[webChannel_id]=192&page=1"),
    ("TravelChannel.com", "/shows?Show[webChannel_id]=151&page=1"),
    ("Tubi", "/shows?Show[webChannel_id]=401&page=1"),
    ("TV4 Play", "/shows?Show[webChannel_id]=155&page=1"),
    ("TVFPlay", "/shows?Show[webChannel_id]=152&page=1"),
    ("TVNweather", "/shows?Show[webChannel_id]=37&page=1"),
    ("Twit", "/shows?Show[webChannel_id]=102&page=1"),
    ("TYSONPlus", "/shows?Show[webChannel_id]=290&page=1"),
    ("TYT", "/shows?Show[webChannel_id]=189&page=1"),
    ("UFC Fight Pass", "/shows?Show[webChannel_id]=45&page=1"),
    ("UMC", "/shows?Show[webChannel_id]=209&page=1"),
    ("Ustream", "/shows?Show[webChannel_id]=76&page=1"),
    ("V LIVE", "/shows?Show[webChannel_id]=122&page=1"),
    ("Vessel", "/shows?Show[webChannel_id]=92&page=1"),
    ("VidAngel", "/shows?Show[webChannel_id]=388&page=1"),
    ("Videoland", "/shows?Show[webChannel_id]=12&page=1"),
    ("VRV Select", "/shows?Show[webChannel_id]=221&page=1"),
    ("Vudu", "/shows?Show[webChannel_id]=289&page=1"),
    ("WOW Presents", "/shows?Show[webChannel_id]=195&page=1"),
    ("WWE Network", "/shows?Show[webChannel_id]=15&page=1"),
    ("WWNLIVE", "/shows?Show[webChannel_id]=66&page=1"),
    ("Xive TV", "/shows?Show[webChannel_id]=511&page=1"),
    ("YAHOO! View", "/shows?Show[webChannel_id]=5&page=1"),
    ("Yle Areena", "/shows?Show[webChannel_id]=220&page=1"),
    ("Youku", "/shows?Show[webChannel_id]=118&page=1"),
    ("YouTube Premium", "/shows?Show[webChannel_id]=43&page=1"),
    ("YouTube", "/shows?Show[webChannel_id]=21&page=1"),
    ("Zeus", "/shows?Show[webChannel_id]=331&page=1")
]


