

companies = [

    {'name': '20th Century Fox Animation', 'id': 11749, 'image': '/5AzTeZkSCFhiGZ86g2nz8SAHtgy.png'},
    {'name': '20th Century Fox Television', 'id': 1556, 'image': '/31h94rG9hzjprXoYNy3L1ErUya2.png'},
    {'name': '20th Century Fox', 'id': 25, 'image': '/qZCc1lty5FzX30aOCVRBLzaVmcp.png'},
    {'name': 'A24', 'id': 41077, 'image': '/1ZXsGaFPgrgS6ZZGS37AqD5uU12.png'},
    {'name': 'Amblin Entertainment', 'id': 56, 'image': '/cEaxANEisCqeEoRvODv2dO1I0iI.png'},
    {'name': 'American Zoetrope', 'id': 70, 'image': '/ueaENQkPcy8rlr5fGZVBXKOhlBh.png'},
    {'name': 'Anonymous Content', 'id': 10039, 'image': '/b8w4LldQolMKiLZw4FQJBcXSDGI.png'},
    {'name': 'ARTE France Cinema', 'id': 94, 'image': '/huC7HqorvUThGIrENrbcHmQVUA0.png'},
    {'name': 'ARTE', 'id': 201, 'image': '/6UIpEURdjnmcJPwgTDRzVRuwADr.png'},
    {'name': 'Automatik Entertainment', 'id': 7625, 'image': '/kzq4ibnNeZrp00zpBWv3st1QCOh.png'},
    {'name': 'BBC Films', 'id': 288, 'image': '/wdmwQuV4R1MIr8A78izZkC184uC.png'},
    {'name': 'BFI Film Fund', 'id': 16877, 'image': '/pR2SnHFl7BvRIUuauFJrxXFYjeU.png'},
    {'name': 'BFI', 'id': 7281, 'image': '/lkqIuaKTm2sg3umwTBScmqyzLX5.png'},
    {'name': 'Blumhouse Productions', 'id': 3172, 'image': '/kDedjRZwO8uyFhuHamomOhN6fzG.png'},
    {'name': 'Blumhouse Television', 'id': 68884, 'image': '/1BYexT6Vikz4ulCcYKGPmOi6Jm0.png'},
    {'name': 'Bron Studios', 'id': 13240, 'image': '/aTc07YaNHo8WNgkQSnvLmG6w4nW.png'},
    {'name': 'Buena Vista Pictures', 'id': 32, 'image': None},
    {'name': 'Canal+', 'id': 104, 'image': '/9aotxauvc9685tq9pTcRJszuT06.png'},
    {'name': 'Caravan Pictures', 'id': 175, 'image': '/trtXLj3zv8T9ke1Vhw4SCkkM4JJ.png'},
    {'name': 'Castle Rock Entertainment', 'id': 97, 'image': '/7znWcbDd4PcJzJUlJxYqAlPPykp.png'},
    {'name': 'Channel Four Films', 'id': 181, 'image': '/zhQ77XOviCBuXd74IurqqjgLNe0.png'},
    {'name': 'Cine+', 'id': 10611, 'image': '/zQ4fGaEnNkWfSzyygXRcUZwPmDG.png'},
    {'name': 'CNC', 'id': 310, 'image': '/4Gp5A4YdjPBfsHT47ngHMaXWmb9.png'},
    {'name': 'Columbia Pictures Corporation', 'id': 106728, 'image': None},
    {'name': 'Columbia Pictures Television', 'id': 3614, 'image': '/qFRpYYtU9iyVKDMpm3a8tN7Q7YE.png'},
    {'name': 'Columbia Pictures', 'id': 5, 'image': '/71BqEFAF4V3qjjMPCpLuyJFB9A.png'},
    {'name': 'Constantin Film', 'id': 47, 'image': '/i7Z9ot2o3N5Sa3HrF09kniFs2y8.png'},
    {'name': 'Creative Scotland', 'id': 8087, 'image': None},
    {'name': 'Davis Entertainment', 'id': 1302, 'image': '/kQZtJdyphCmq292iGDqlUx0yk2D.png'},
    {'name': 'DC Comics', 'id': 429, 'image': '/2Tc1P3Ac8M479naPp1kYT3izLS5.png'},
    {'name': 'DC Entertainment', 'id': 9993, 'image': '/2Tc1P3Ac8M479naPp1kYT3izLS5.png'},
    {'name': 'DC Films', 'id': 128064, 'image': '/13F3Jf7EFAcREU0xzZqJnVnyGXu.png'},
    {'name': 'DreamWorks Animation', 'id': 521, 'image': '/kP7t6RwGz2AvvTkvnI1uteEwHet.png'},
    {'name': 'DreamWorks Pictures', 'id': 7, 'image': '/vru2SssLX3FPhnKZGtYw00pVIS9.png'},
    {'name': 'Dune Entertainment III', 'id': 6332, 'image': '/42UPdZl6B2cFXgNUASR8hSt9mpS.png'},
    {'name': 'Dune Entertainment', 'id': 444, 'image': '/42UPdZl6B2cFXgNUASR8hSt9mpS.png'},
    {'name': 'Eddie Murphy Productions', 'id': 30, 'image': None},
    {'name': 'EFO Films', 'id': 10405, 'image': None},
    {'name': 'Entertainment One', 'id': 8147, 'image': '/q6HOAdSNgCbeOqwoMVRc6REgbXF.png'},
    {'name': 'Eurimages', 'id': 850, 'image': '/aF7qajGJGtMpdrtvssM9g90YanX.png'},
    {'name': 'Film4 Productions', 'id': 6705, 'image': '/e8EXNSfwr5E9d3TR8dHKbQnQK4W.png'},
    {'name': 'Film i Vast', 'id': 2801, 'image': '/bswb1PLLsKDUXMLgy42bZtCtIde.png'},
    {'name': 'Filmgate Films', 'id': 18230, 'image': None},
    {'name': 'FilmNation Entertainment', 'id': 7493, 'image': '/452FO4LcI6lA6bfgl6w1kQYRBlr.png'},
    {'name': 'Fine Line Features', 'id': 8, 'image': '/78ilmDNTpdCfsakrsLqmAUkFTrO.png'},
    {'name': 'Focus Features', 'id': 10146, 'image': '/xnFIOeq5cKw09kCWqV7foWDe4AA.png'},
    {'name': 'Fox 2000 Pictures', 'id': 711, 'image': '/tEiIH5QesdheJmDAqQwvtN60727.png'},
    {'name': 'Fox Searchlight Pictures', 'id': 43, 'image': '/4RgIPr55kBakgupWkzdDxqXJEqr.png'},
    {'name': 'France 2 Cinema', 'id': 83, 'image': '/9OQ0rm55xtlgX7KcAKMUePJSrQc.png'},
    {'name': 'France 3 Cinema', 'id': 591, 'image': '/q5I5RDwMEiqoNmfaJgd2LraEOJY.png'},
    {'name': 'Gaumont', 'id': 9, 'image': '/nda3dTUYdDrJ6rZqBpYvY865aDv.png'},
    {'name': 'Gaumont-British Picture Corporation', 'id': 4978, 'image': None},
    {'name': 'Gold Circle Films', 'id': 12026, 'image': None},
    {'name': 'Gramercy Pictures', 'id': 37, 'image': '/nlG4JEjJ7SAFDehgIVvHFBPW23y.png'},
    {'name': 'Gravitas Ventures', 'id': 44632, 'image': '/neCKH4sJCBhZ1B4QocTM4VXCQOR.png'},
    {'name': 'Grindstone Entertainment Group', 'id': 3604, 'image': '/jC6Hk3ZyNRlVPJsA0xGlAhgd2RP.png'},
    {'name': 'Hallmark Entertainment', 'id': 4056, 'image': None},
    {'name': 'Hallmark Hall of Fame Productions', 'id': 9027, 'image': '/eGT7RxXHIyhByHpZmv4WxBwoWAl.png'},
    {'name': 'HanWay Films', 'id': 2395, 'image': '/pZz4qs03FtP6UGtZ3hjQ6qimcwi.png'},
    {'name': 'Happy Madison Productions', 'id': 2608, 'image': '/g3YRudXiQzHesQqRXvnhFpMzfkU.png'},
    {'name': 'Head Gear Films', 'id': 5056, 'image': '/kADFcjL04xe5HGBnlLjbfhliS2a.png'},
    {'name': 'IFC Films', 'id': 307, 'image': '/gUi3pAUznQJpR296lw4mSVbB7zx.png'},
    {'name': 'IFC Midnight', 'id': 70784, 'image': '/17G3JkSIjyFBbvSkmk0xPf6pysm.png'},
    {'name': 'IM Global', 'id': 7437, 'image': '/e5CcgFrdlxMUwlsS72si8q1yHBr.png'},
    {'name': 'Imagine Entertainment', 'id': 23, 'image': '/mkxNjThahj5pvntvYKVpMbWXm3D.png'},
    {'name': 'Ingenious Media', 'id': 290, 'image': '/Q8mw2AOQQc8Qg0uNwLWq86DVZv.png'},
    {'name': 'Jerry Bruckheimer Films', 'id': 130, 'image': '/c9dVHPOL3cqCr2593Ahk0nEKTEM.png'},
    {'name': 'Jerry Bruckheimer Films/Don Simpson', 'id': 10288, 'image': None},
    {'name': 'JVC', 'id': 182, 'image': None},
    {'name': 'Lakeshore Entertainment', 'id': 126, 'image': '/kADPanRDkKTxncPXXVahvHPUvCj.png'},
    {'name': 'Legendary Pictures', 'id': 923, 'image': '/5UQsZrfbfG2dYJbx8DxfoTr2Bvu.png'},
    {'name': 'Lifetime', 'id': 3431, 'image': '/6LVLYfZAEQfhJey0MGvhFXdDEK1.png'},
    {'name': 'Lions Gate Films', 'id': 35, 'image': '/wxrHa3nZ1K4zo65p56991INkGo6.png'},
    {'name': 'Lionsgate', 'id': 1632, 'image': '/cisLn1YAUuptXVBa0xjq7ST9cH0.png'},
    {'name': 'Lipsync Productions', 'id': 9987, 'image': '/o5OTKAw7Acl5fTZYPyl8M8D9570.png'},
    {'name': 'Lucasfilm Ltd.', 'id': 1, 'image': '/o86DbpburjxrqAzEDhXZcyE8pDb.png'},
    {'name': 'Magnolia Pictures', 'id': 1030, 'image': '/bus7KzJshT0VMXuKR7dwK5bqPSO.png'},
    {'name': 'Malpaso Productions', 'id': 171, 'image': None},
    {'name': 'Marvel Animation', 'id': 13252, 'image': '/aGeUvfSNA8gRl6ZjvmLQOsb7PMw.png'},
    {'name': 'Marvel Enterprises', 'id': 19551, 'image': '/2WpWp9b108hizjHKdA107hFmvQ5.png'},
    {'name': 'Marvel Entertainment', 'id': 7505, 'image': '/837VMM4wOkODc1idNxGT0KQJlej.png'},
    {'name': 'Marvel Knights', 'id': 11106, 'image': '/h4XR8uTNylVX9hJTiN50e76booZ.png'},
    {'name': 'Marvel Productions', 'id': 2301, 'image': '/qdPhBEP8sjK3Eb3rKc94554gcZt.png'},
    {'name': 'Marvel Studios', 'id': 420, 'image': '/hUzeosd33nzE5MCNsZxCGEKTXaQ.png'},
    {'name': 'Metro-Goldwyn-Mayer', 'id': 21, 'image': '/aOWKh4gkNrfFZ3Ep7n0ckPhoGb5.png'},
    {'name': 'Metrol Technology', 'id': 25954, 'image': None},
    {'name': 'MGM Television', 'id': 2230, 'image': '/8UHPNZnCf2gfHs9DrSvJMa8t7Ry.png'},
    {'name': 'Millennium Films', 'id': 1020, 'image': '/kuUIHNwMec4dwOLghDhhZJzHZTd.png'},
    {'name': 'Miramax', 'id': 14, 'image': '/m6AHu84oZQxvq7n1rsvMNJIAsMu.png'},
    {'name': 'New Line Cinema', 'id': 12, 'image': '/iaYpEp3LQmb8AfAtmTvpqd4149c.png'},
    {'name': 'New Regency Pictures', 'id': 10104, 'image': '/hNuGhsKVlmhnwSRcmOejDBDjh6w.png'},
    {'name': 'NPV Entertainment', 'id': 172, 'image': None},
    {'name': 'Original Film', 'id': 333, 'image': '/5xUJfzPZ8jWJUDzYtIeuPO4qPIa.png'},
    {'name': 'Orion Pictures', 'id': 41, 'image': '/AuAIlCWBrbhbUFFrJ6M9E3ihBoj.png'},
    {'name': 'Paramount', 'id': 4, 'image': '/fycMZt242LVjagMByZOLUGbCvv3.png'},
    {'name': 'Participant', 'id': 6735, 'image': '/pAQW38WU8ychBvYU2aGPTEbynEN.png'},
    {'name': 'Passion Pictures', 'id': 11594, 'image': '/4w31g1L8zrpOuZ7s7f83qkmfOVZ.png'},
    {'name': 'Pathe Distribution', 'id': 3012, 'image': None},
    {'name': 'Pathe Pictures International', 'id': 1178, 'image': None},
    {'name': 'Pathe Renn Productions', 'id': 866, 'image': None},
    {'name': 'Pathe', 'id': 7981, 'image': '/6Yv1gIAuGkHS5Vis4UjnqHhCPWV.png'},
    {'name': 'Perfect World Pictures', 'id': 10338, 'image': '/el2ap6lvjcEDdbyJoB3oKiYgXu9.png'},
    {'name': 'Pixar', 'id': 3, 'image': '/1TjvGVDMYsj6JBxOAkUHpPEwLf7.png'},
    {'name': 'Plan B Entertainment', 'id': 81, 'image': '/8wOfUhA7vwU2gbPjQy7Vv3EiF0o.png'},
    {'name': 'RAI Cinema', 'id': 155990, 'image': '/py9VaywwK6KVi94YwrxSKVg1gkh.png'},
    {'name': 'RAI', 'id': 1583, 'image': '/gKP4egMJOi5rksdnplfPV1wa0sd.png'},
    {'name': 'RatPac Entertainment', 'id': 41624, 'image': '/wzKxIeQKlMP0y5CaAw25MD6EQmf.png'},
    {'name': 'Regency Enterprises', 'id': 508, 'image': '/7PzJdsLGlR7oW4J0J5Xcd0pHGRg.png'},
    {'name': 'Relativity Media', 'id': 7295, 'image': '/5MYE96QiE5a5oFhXxFb4y8ILSpw.png'},
    {'name': 'Revolution Films', 'id': 163, 'image': None},
    {'name': 'Revolution Studios', 'id': 497, 'image': '/pMyhOBd3sCiLzBlmIopdJkcUFtn.png'},
    {'name': 'Rhombus Media', 'id': 164, 'image': '/v3zcUepvKC7Vz36yjklk1rw6k8Q.png'},
    {'name': 'RKO Radio Pictures', 'id': 6, 'image': '/n53F7K9scQWFXYbrCablqLKqJdp.png'},
    {'name': 'Rogue Pictures', 'id': 134, 'image': None},
    {'name': 'Saban Films', 'id': 76992, 'image': '/mw3j3P8SUQJKLSJQrLKuSDO9Xr6.png'},
    {'name': 'Samuel Goldwyn Films', 'id': 9118, 'image': '/9o6KLcDBRw3fNItUflJVwj8dZpC.png'},
    {'name': 'Scott Free Productions', 'id': 1645, 'image': '/6Ry6uNBaa0IbbSs1XYIgX5DkA9r.png'},
    {'name': 'Scott Rudin Productions', 'id': 258, 'image': None},
    {'name': 'Screen Australia', 'id': 7584, 'image': '/eGkfvvyf4fJTvBUR1xt1669IPA3.png'},
    {'name': 'Screen Gems', 'id': 3287, 'image': '/bz6GbCQQXGNE56LTW9dwgksW0Iw.png'},
    {'name': 'Screen Ireland', 'id': 1898, 'image': '/a2gst8022qi5g3sFxJIWeKVd2aK.png'},
    {'name': 'Sony Pictures Animation', 'id': 2251, 'image': '/6l16UFSkZ1oPpyBYaILgffFZlTc.png'},
    {'name': 'Sony Pictures Classics', 'id': 58, 'image': '/voYCwlBHJQANtjvm5MNIkCF1dDH.png'},
    {'name': 'Sony Pictures', 'id': 34, 'image': '/GagSvqWlyPdkFHMfQ3pNq6ix9P.png'},
    {'name': 'Spyglass Entertainment', 'id': 158, 'image': '/6SHlNIype9zmyEMRsBtoueUtLsq.png'},
    {'name': 'StudioCanal', 'id': 694, 'image': '/5LEHONGkZBIoWvp1ygHOF8iyi1M.png'},
    {'name': 'Summit Entertainment', 'id': 491, 'image': '/rUp0lLKa1pr4UsPm8fgzmnNGxtq.png'},
    {'name': 'Temple Hill Entertainment', 'id': 12292, 'image': '/llGRXF5WYUW2fzXg0ebCoKMXjmT.png'},
    {'name': 'The Fyzz', 'id': 36109, 'image': '/wca0Jcidf2N1KAPicYMjGoKOmYu.png'},
    {'name': 'The Weinstein Company', 'id': 308, 'image': '/e8F3mQM7DkJ5SfYYDp8FYzPBOGX.png'},
    {'name': 'Touchstone Pictures', 'id': 9195, 'image': '/ou5BUbtulr6tIt699q6xJiEQTR9.png'},
    {'name': 'TriStar Pictures', 'id': 559, 'image': '/eC0bWHVjnjUducyA6YFoEFqnPMC.png'},
    {'name': 'TSG Entertainment', 'id': 22213, 'image': '/qx9K6bFWJupwde0xQDwOvXkOaL8.png'},
    {'name': 'Telefilm Canada', 'id': 806, 'image': '/kcNh09qqR2Pkw1JAzRW4CommrW4.png'},
    {'name': 'UK Film Council', 'id': 2452, 'image': '/6CLoZ59fLPG7UyxQtGTqRevjf58.png'},
    {'name': 'United Artists', 'id': 60, 'image': '/oJXpAs4I3W46e4dkaOEzCa4yBko.png'},
    {'name': 'Universal Pictures', 'id': 33, 'image': '/8lvHyhjr8oUKOOy2dKXoALWKdp0.png'},
    {'name': 'Vertical Entertainment', 'id': 88606, 'image': '/3w49QoRwptUujWxSjcR3iEr1XSU.png'},
    {'name': 'Village Roadshow Entertainment', 'id': 13675, 'image': None},
    {'name': 'Village Roadshow Pictures', 'id': 79, 'image': '/tpFpsqbleCzEE2p5EgvUq6ozfCA.png'},
    {'name': 'Voltage Pictures', 'id': 6626, 'image': '/A1BnMoWjzjOrjzpWimyBQkf84mS.png'},
    {'name': 'Walt Disney Animation Studios', 'id': 6125, 'image': '/tVPmo07IHhBs4HuilrcV0yujsZ9.png'},
    {'name': 'Walt Disney Pictures', 'id': 2, 'image': '/wdrCwmRnLFJhEoH8GSfymY85KHT.png'},
    {'name': 'Walt Disney Productions', 'id': 3166, 'image': '/vyyv4Gy9nPqAZKElPm2izLlEaVS.png'},
    {'name': 'Walt Disney Television', 'id': 670, 'image': '/rRGi5UkwvdOPSfr5Xf42RZUsYgd.png'},
    {'name': 'Warner Bros. Animation', 'id': 2785, 'image': '/l5zW8jjmQOCx2dFmvnmbYmqoBmL.png'},
    {'name': 'Warner Bros. Cartoons', 'id': 8298, 'image': '/r6cuEYq7DqrHCNVa7vSanTS0cuw.png'},
    {'name': 'Warner Bros. Entertainment', 'id': 17, 'image': '/s1y7CTv6YHe87YUGOq6SRB6DmO7.png'},
    {'name': 'Warner Bros. Japan', 'id': 3627, 'image': '/i1eW4O13B28b4JHpIL5C9rRiiur.png'},
    {'name': 'Warner Bros. Pictures', 'id': 174, 'image': '/IuAlhI9eVC9Z8UQWOIDdWRKSEJ.png'},
    {'name': 'Warner Bros. Television', 'id': 1957, 'image': '/3T19XSr6yqaLNK8uJWFImPgRax0.png'},
    {'name': 'WDR', 'id': 46, 'image': '/3xFdKHLXPGHEbrAkmsepGE8974Y.png'},
    {'name': 'WDR/Arte', 'id': 10946, 'image': '/gk4SFkJ3G49gGL308zymD8QGNw.png'},
    {'name': 'Wild Bunch', 'id': 856, 'image': '/3tfzS2CrX6Ntbu927XzHXEPDA6y.png'},
    {'name': 'WingNut Films', 'id': 11, 'image': '/6FAuASQHybRkZUk08p9PzSs9ezM.png'},
    {'name': 'Working Title Films', 'id': 10163, 'image': '/16KWBMmfPX0aJzDExDrPxSLj0Pg.png'},
    {'name': 'X Filme Creative Pool', 'id': 96, 'image': '/9ps82gVzUeNdkjmLzoGDQLiLDio.png'},
    {'name': 'XYZ Films', 'id': 12142, 'image': '/rPnEeMwxjI6rYMGqkWqIWwIJXxi.png'},
    {'name': 'ZDF', 'id': 4606, 'image': '/otZHbf1HmzLRQsZFSqJXkf8EHz7.png'},
    {'name': 'ZDF/Arte', 'id': 11237, 'image': None},
    {'name': 'Zentropa Entertainments', 'id': 76, 'image': '/nebkQYtQKhZyHJfh5v0oGpNbPzu.png'}

]


