

networks = [
    {'name': 'A&E', 'id': 129, 'origin_country': 'US'},
    {'name': 'ABC Family', 'id': 75, 'origin_country': 'US'},
    {'name': 'ABC', 'id': 2, 'origin_country': 'US'},
    {'name': 'ABC', 'id': 18, 'origin_country': 'AU'},
    {'name': 'Adult Swim', 'id': 80, 'origin_country': 'US'},
    {'name': 'Amazon', 'id': 1024, 'origin_country': ''},
    {'name': 'AMC', 'id': 174, 'origin_country': 'US'},
    {'name': 'Animal Planet', 'id': 91, 'origin_country': 'US'},
    {'name': 'Apple TV+', 'id': 2552, 'origin_country': 'US'},
    {'name': 'BBC America', 'id': 493, 'origin_country': 'US'},
    {'name': 'BBC Four', 'id': 100, 'origin_country': 'GB'},
    {'name': 'BBC One', 'id': 4, 'origin_country': 'GB'},
    {'name': 'BBC Scotland', 'id': 3278, 'origin_country': 'GB'},
    {'name': 'BBC Television', 'id': 3546, 'origin_country': 'GB'},
    {'name': 'BBC Three', 'id': 3, 'origin_country': 'GB'},
    {'name': 'BBC Two', 'id': 332, 'origin_country': 'GB'},
    {'name': 'BET', 'id': 24, 'origin_country': 'US'},
    {'name': 'BET+', 'id': 3343, 'origin_country': 'US'},
    {'name': 'Blackpills', 'id': 2097, 'origin_country': ''},
    {'name': 'Boomerang', 'id': 523, 'origin_country': 'US'},
    {'name': 'Bravo', 'id': 74, 'origin_country': 'US'},
    {'name': 'Cartoon Network', 'id': 56, 'origin_country': 'US'},
    {'name': 'CBC Television', 'id': 23, 'origin_country': 'CA'},
    {'name': 'CBS All Access', 'id': 1709, 'origin_country': 'US'},
    {'name': 'CBS', 'id': 16, 'origin_country': 'US'},
    {'name': 'Cinemax', 'id': 359, 'origin_country': 'US'},
    {'name': 'Comedy Central', 'id': 47, 'origin_country': 'US'},
    {'name': 'Cooking Channel', 'id': 802, 'origin_country': 'US'},
    {'name': 'Crackle', 'id': 928, 'origin_country': 'US'},
    {'name': 'Crunchyroll', 'id': 1112, 'origin_country': ''},
    {'name': 'CTV', 'id': 110, 'origin_country': 'CA'},
    {'name': 'CuriosityStream', 'id': 2349, 'origin_country': 'US'},
    {'name': 'CW seed', 'id': 1049, 'origin_country': 'US'},
    {'name': 'DC Universe', 'id': 2243, 'origin_country': 'US'},
    {'name': 'Discovery Family', 'id': 1287, 'origin_country': 'US'},
    {'name': 'Discovery Kids', 'id': 22, 'origin_country': 'US'},
    {'name': 'Discovery', 'id': 64, 'origin_country': 'US'},
    {'name': 'Discovery', 'id': 106, 'origin_country': 'CA'},
    {'name': 'Discovery', 'id': 1079, 'origin_country': 'GB'},
    {'name': 'discovery+', 'id': 4353, 'origin_country': 'US'},
    {'name': 'Disney Channel', 'id': 54, 'origin_country': 'US'},
    {'name': 'Disney Junior', 'id': 281, 'origin_country': 'US'},
    {'name': 'Disney XD', 'id': 44, 'origin_country': 'US'},
    {'name': 'Disney+', 'id': 2739, 'origin_country': 'US'},
    {'name': 'E!', 'id': 76, 'origin_country': 'US'},
    {'name': 'Epix', 'id': 922, 'origin_country': 'US'},
    {'name': 'ESPN', 'id': 29, 'origin_country': 'US'},
    {'name': 'Facebook Watch', 'id': 2371, 'origin_country': ''},
    {'name': 'FOX', 'id': 19, 'origin_country': 'US'},
    {'name': 'Freeform', 'id': 1267, 'origin_country': 'US'},
    {'name': 'Fuji TV', 'id': 1, 'origin_country': 'JP'},
    {'name': 'Funimation Channel', 'id': 728, 'origin_country': 'US'},
    {'name': 'FX', 'id': 88, 'origin_country': 'US'},
    {'name': 'FXX', 'id': 1035, 'origin_country': 'US'},
    {'name': 'fyi', 'id': 1080, 'origin_country': 'US'},
    {'name': 'Hallmark Channel', 'id': 384, 'origin_country': 'US'},
    {'name': 'HBO Max', 'id': 3186, 'origin_country': 'US'},
    {'name': 'HBO', 'id': 49, 'origin_country': 'US'},
    {'name': 'History', 'id': 65, 'origin_country': 'US'},
    {'name': 'History', 'id': 1755, 'origin_country': 'GB'},
    {'name': 'Hulu', 'id': 453, 'origin_country': 'US'},
    {'name': 'Hulu', 'id': 1772, 'origin_country': 'JP'},
    {'name': 'IMDb TV', 'id': 4042, 'origin_country': 'US'},
    {'name': 'Investigation Discovery', 'id': 244, 'origin_country': 'US'},
    {'name': 'ITV', 'id': 9, 'origin_country': 'GB'},
    {'name': 'Kids WB', 'id': 3932, 'origin_country': ''},
    {'name': 'Lifetime', 'id': 34, 'origin_country': 'US'},
    {'name': 'MBS', 'id': 94, 'origin_country': 'JP'},
    {'name': 'MTV2', 'id': 17, 'origin_country': 'US'},
    {'name': 'MTV', 'id': 33, 'origin_country': 'US'},
    {'name': 'Nat Geo Wild', 'id': 1043, 'origin_country': 'US'},
    {'name': 'National Geographic', 'id': 43, 'origin_country': 'US'},
    {'name': 'NBC', 'id': 6, 'origin_country': 'US'},
    {'name': 'Netflix', 'id': 213, 'origin_country': ''},
    {'name': 'Nick at Nite', 'id': 259, 'origin_country': 'US'},
    {'name': 'Nick Jr.', 'id': 35, 'origin_country': 'US'},
    {'name': 'Nickelodeon', 'id': 13, 'origin_country': 'US'},
    {'name': 'Nicktoons', 'id': 224, 'origin_country': 'US'},
    {'name': 'OWN', 'id': 827, 'origin_country': 'US'},
    {'name': 'Paramount Network', 'id': 2076, 'origin_country': 'US'},
    {'name': 'Paramount+', 'id': 4330, 'origin_country': 'US'},
    {'name': 'PBS Kids', 'id': 122, 'origin_country': 'US'},
    {'name': 'PBS', 'id': 14, 'origin_country': 'US'},
    {'name': 'Peacock', 'id': 3353, 'origin_country': 'US'},
    {'name': 'Playstation Network', 'id': 1029, 'origin_country': ''},
    {'name': 'Quibi', 'id': 3091, 'origin_country': 'US'},
    {'name': 'Rooster Teeth', 'id': 1356, 'origin_country': 'US'},
    {'name': 'Showcase', 'id': 105, 'origin_country': 'CA'},
    {'name': 'Showtime', 'id': 67, 'origin_country': 'US'},
    {'name': 'Spike', 'id': 55, 'origin_country': 'US'},
    {'name': 'Starz', 'id': 318, 'origin_country': 'US'},
    {'name': 'Syfy', 'id': 77, 'origin_country': 'US'},
    {'name': 'TBS', 'id': 68, 'origin_country': 'US'},
    {'name': 'TeenNick', 'id': 234, 'origin_country': 'US'},
    {'name': 'Teletoon', 'id': 83, 'origin_country': 'CA'},
    {'name': 'The CW', 'id': 71, 'origin_country': 'US'},
    {'name': 'The Roku Channel', 'id': 4692, 'origin_country': 'US'},
    {'name': 'The WB', 'id': 21, 'origin_country': 'US'},
    {'name': 'TLC', 'id': 84, 'origin_country': 'US'},
    {'name': 'TNT', 'id': 41, 'origin_country': 'US'},
    {'name': 'Toon Disney', 'id': 142, 'origin_country': 'US'},
    {'name': 'Travel Channel', 'id': 209, 'origin_country': 'US'},
    {'name': 'truTV', 'id': 364, 'origin_country': 'US'},
    {'name': 'TV Land', 'id': 397, 'origin_country': 'US'},
    {'name': 'TV Tokyo', 'id': 98, 'origin_country': 'JP'},
    {'name': 'USA Network', 'id': 30, 'origin_country': 'US'},
    {'name': 'Viceland', 'id': 1339, 'origin_country': 'US'},
    {'name': 'WGN America', 'id': 202, 'origin_country': 'US'},
    {'name': 'WWE Network', 'id': 1025, 'origin_country': 'US'},
    {'name': 'YouTube', 'id': 247, 'origin_country': ''},
    {'name': 'YouTube Premium', 'id': 1436, 'origin_country': 'US'}
]


